name: Login to github container registry

on:
  workflow_dispatch:

jobs:

  login-to-github-container-registry:

    runs-on: ubuntu-latest

    steps:
      - name: Try to login with ${{ github.actor }} and ${{ secrets.GITHUB_TOKEN }}
        run: echo "Hello"
      - name: Login to Docker Hub
      - uses: docker/login-action@v1
      - with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
