name: 

on:
  workflow_dispatch:
    inputs:      
      publish-on-success:
        required: false
        type: boolean
        description: indicates whether to publish the artificats

jobs:

  greet:
   
    runs-on: ubuntu-latest 
                             
    steps:
    - name: print input value
      run: echo  "User input is ${{github.event.inputs.publish-on-success}} which evaluates to ${{github.event.inputs.publish-on-success == 'true'}}"
    - name: publish if true
      if: github.event.inputs.publish-on-success == 'true'
      run: echo "Publishing now"    
